# SPDX-FileCopyrightText: Copyright (c) 2024 Ferrous Systems
# SPDX-License-Identifier: MIT OR Apache-2.0

[target.armv7r-none-eabihf]
rustflags = [
    "-Clink-arg=-Tlinker.ld",
    "-Clink-arg=-Tdefmt.x",
    "-Ctarget-cpu=cortex-r5",
]
runner = "./qemu_run.sh"

[build]
target = ["armv7r-none-eabihf"]
