# SPDX-FileCopyrightText: Copyright (c) 2026 Ferrous Systems
# SPDX-License-Identifier: MIT OR Apache-2.0

[toolchain]
channel = "stable"
components = [ "llvm-tools-preview", "clippy" ]
targets = ["thumbv8m.main-none-eabihf"]
profile = "default"
