# Copyright (c) 2026 Ferrous Systems
# SPDX-License-Identifier: MIT OR Apache-2.0

name: workflow-check-with-ferrocene
run-name: Check with Ferrocene
on:
  push:
    branches: [main]
  pull_request: {}
  workflow_dispatch: {}
jobs:
  job-build:
    strategy:
      matrix:
        build:
          - package: nrf52-app
            target: thumbv7em-none-eabihf
          - package: qemu-cortex-r5-app
            target: armv7r-none-eabihf
    runs-on: ubuntu-latest
    steps:
      - name: Install Arm C compiler
        run: |
          sudo apt-get update -y && sudo apt-get -y install gcc-arm-none-eabi
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/ferrocene/criticalup/releases/download/v1.6.0/criticalup-installer.sh | sh
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          submodules: 'true'
      - name: Install Ferrocene
        env:
          CRITICALUP_TOKEN: ${{ secrets.CRITICALUP_TOKEN }}
        run: |
          criticalup install
          echo "$HOME/.local/share/criticalup/bin" >> $GITHUB_PATH
      - name: Find slug name
        run: |
          slug=$(./describe.sh "${GITHUB_REF}")
          echo "Building with slug '${slug}'"
          echo "BUILD_SLUG=${slug}" >> "${GITHUB_ENV}"
      - name: Build nRF52 App
        run: |
          cd ${{ matrix.build.package }}
          criticalup run rustc --version
          criticalup run cargo --version
          criticalup run cargo build --release
      - name: Upload nrf52-app
        uses: actions/upload-artifact@v7
        with:
          name: ferrocene-${{ matrix.build.package}}
          path: ${{ matrix.build.package}}/target/${{ matrix.build.target }}/release/${{ matrix.build.package}}
  job-all:
    runs-on: ubuntu-latest
    if: always()
    # NOTE: Jobs that must pass this workflow must be listed here
    needs:
      - job-build
    timeout-minutes: 2
    steps:
      # Taken from: https://github.com/orgs/community/discussions/75568#discussioncomment-10351973
      - name: Ensure all required jobs succeed
        run: |
          echo "Our needs:"
          echo '${{ toJSON(needs) }}'
          echo "Checking..."
          echo '${{ toJSON(needs) }}' | jq -e 'to_entries | all(.value.result == "success")'
