# Copyright (c) 2026 Ferrous Systems
# SPDX-License-Identifier: MIT OR Apache-2.0

name: workflow-build-everything
run-name: Build Everything
on:
  push:
    branches: [main]
  pull_request: {}
  workflow_dispatch: {}
jobs:
  job-build:
    strategy:
      matrix:
        build:
          - package: nrf52-app
            target: thumbv7em-none-eabihf
          - package: qemu-cortex-r5-app
            target: armv7r-none-eabihf
    runs-on: ubuntu-latest
    steps:
      - name: Install Arm C compiler
        run: |
          sudo apt-get update -y && sudo apt-get -y install gcc-arm-none-eabi
      - name: Install tools
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/knurling-rs/flip-link/releases/download/v0.1.12/flip-link-installer.sh | sh
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          submodules: 'true'
      - name: Add rustup target
        run: |
          rustup target add ${{ matrix.build.target }}
      - name: Find slug name
        run: |
          slug=$(./describe.sh "${GITHUB_REF}")
          echo "Building with slug '${slug}'"
          echo "BUILD_SLUG=${slug}" >> "${GITHUB_ENV}"
      - name: Build
        run: |
          cd ${{ matrix.build.package }}
          cargo build --target=${{ matrix.build.target }} --release
      - name: Upload ${{ matrix.build.package }}
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.build.package }}
          path: ${{ matrix.build.package }}/target/${{ matrix.build.target }}/release/${{ matrix.build.package }}
