# Copyright (c) 2026 Ferrous Systems
# SPDX-License-Identifier: MIT OR Apache-2.0

name: workflow-code-format
run-name: Check code formatting
on:
  push:
    branches: [main]
  pull_request: {}
  workflow_dispatch: {}
jobs:
  job-format:
    strategy:
      matrix:
        build:
          - package: nrf52-app
          - package: qemu-cortex-r5-app
          - package: threadx-sys
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
      - name: Check Formatting
        run: |
          cd ${{ matrix.build.package }}
          cargo fmt -- --check
